name: merging_of_applications
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_phone_direct_caller: ^2.1.1
  curved_navigation_bar: ^1.0.6
  cached_network_image: ^3.0.0
  rick_and_morty_api: ^0.1.3
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.8
  on_audio_query: ^2.9.0
  url_launcher: ^6.3.0
  just_audio: ^0.9.40
  direct_sms: ^0.0.1
  skeletons: ^0.0.3
  http: ^1.2.2
  dio: ^5.7.0
  permission_handler: ^11.3.1
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bajo.jpg
    - assets/images/fuerte.jpg
    - assets/images/normal.jpg

